config/routes.rb
Rails.application.routes.draw do

  resources :estado_academicos

  resources :regionales

	devise_for :usuarios, :controllers => {:registrations => "registrations"}

  resources :colaboradores

  resources :detalle_presupuestos#, only: [:index, :show, :edit, :update, :destroy]

  resources :historial_estado_presupuestos

  resources :presupuestos do
    resources :detalle_presupuestos#, only: [:new, :create]
  end

  resources :detalle_gastos

  resources :transacciones

  resources :sesiones

  resources :historial_estado_usuarios

  resources :asignacion_funciones

  resources :asistencia_eventos

  resources :asignacion_rol_predefinidos

  resources :privilegios

  resources :notificacion_sistemas

  resources :notificacion_emailes

  resources :notificaciones

  resources :evento_publicos

  resources :informe_gastos do
    resources :detalle_gastos #, only: [:new, :create]
  end

  resources :detalle_restricciones

  resources :restricciones

  resources :postulaciones do
	  member do
	    post 'aceptar'
	  end
  end

  resources :notas

  resources :asignacion_roles do
	resources :reportes
  end

  resources :roles

  

  resources :reportes

  resources :asignacion_actividades

  resources :requisitos

  resources :habilidades

  resources :notificacion_predeterminadas

  resources :historial_estado_actividades

  resources :actividades do
  	resources :historial_estado_actividades
  	resources :asignacion_actividades
  end

  resources :objetivo_especificos do
    resources :actividades
  end

  resources :objetivo_generales do
    resources :objetivo_especificos
  end

  resources :historial_estado_proyectos

  resources :proyectos do
	  member do
		  get :agregar_necesidad
	  end
    resources :asignacion_roles
    resources :notificacion_predeterminadas
    resources :historial_estado_proyectos

    get 'notificaciones_predeterminadas' => 'notificacion_predeterminadas#notificaciones_predeterminadas', :as => 'notificaciones_predeterminadas'

    resources :objetivo_generales
    resources :postulaciones
    resources :colaboradores

  end

  resources :necesidades

  resources :voluntarios do
    resources :experiencias 
    resources :horario_disponibles
    resources :notas
   
  end

  resources :horario_disponibles
  
  resources :experiencias
  

  
    get 'buscar_por_legajo/:legajo' => 'voluntarios#buscar_por_legajo'
    get 'buscar_usuario'=>'usuarios#buscar_usuario'
  
  
   get 'buscar_voluntario'=>'voluntarios#buscar_usuario'

  get 'cronograma_actividades'=>'actividades#cronograma_actividades'

  resources :usuarios do
      resources :notificacion_sistemas
  end

  resources :tipo_privilegios

  resources :concepto_gastos

  resources :estado_usuarios

  resources :estado_presupuestos

  resources :tipo_transacciones

  resources :comprobantes

  resources :organizacion_externas

  resources :tipo_roles

  resources :tipo_habilidades do
    resources :habilidades
  end

  resources :tipo_actividades

  resources :tipo_notificaciones

  resources :estvlado_actividades

  resources :tipo_proyectos

  resources :estado_proyectos
  get 'adminitrar_estado_usuario/'  => 'voluntarios#adminitrar_estado_usuario',:as => 'adminitrar_estado_usuario'
  get 'mis_notas/'  => 'voluntarios#mis_notas',:as => 'mis_notas'
  get 'Responder/' => 'notas#Responder',:as =>'Responder'
  get 'buscarusuario/'  => 'voluntarios#buscarusuario',:as => 'buscarusuario'
  get 'buscarusuario/'  => 'voluntarios#buscar_usuario'
  get 'dar_alta_voluntario' => 'usuarios#dar_alta_voluntario', :as => 'dar_alta_voluntario'

  get 'mis_proyectos', :as => 'proyectos/mis_proyectos', :controller => :proyectos
  get 'mis_necesidades', :as => 'necesidades/mis_necesidades', :controller => :necesidades
  
  get 'asignacion_actividad/busqueda_filtrada', :to => 'asignacion_actividades#busqueda_filtrada'

  get 'gestionar_experiencias/:id' => 'voluntarios#gestionar_experiencias', :as => 'gestionar_experiencias'

  get 'agregar_habilidad', :controller => :actividades
  get 'historial_estado_proyectos/modificar', to: 'historial_estado_proyectos#modificar'
  
  get 'usuarios_proyecto', :controller => :asignacion_roles
  
  get 'asignacion_actividad/dar_baja', to: 'asignacion_actividades#dar_baja'
  get 'asignacion_rol/dar_baja', to: 'asignacion_roles#dar_baja'

  get 'crear_organizacion_externa', :controller => :proyectos
  get 'gestionar_presupuesto/:id' => 'presupuestos#gestionar_presupuesto', :as => 'gestionar_presupuesto'
  get 'gestionar_informe_gastos/:id' => 'informe_gastos#gestionar_informe_gastos', :as => 'gestionar_informe_gastos'

  get 'gestionar_restricciones' => 'restricciones#gestionar_restricciones', :as => 'gestionar_restricciones'

  get 'horarios_disponibles/:id' => 'voluntarios#gestion_horarios_disponibles', :as => 'gestion_horarios_disponibles'
  get 'gestionar_nota_P/:id'  => 'voluntarios#gestionar_nota_P',:as => 'gestionar_nota_P'
  get 'gestionar_estado_usuario'=> 'voluntarios#gestionar_estado_usuario',:as =>'gestionar_estado_usuario'
 

  get 'gestionar_habilidades' => 'tipo_habilidades#gestionar_habilidades', :as => 'gestionar_habilidades'

	get 'control_usuario' => 'transacciones#control_usuario', :as => 'control_usuario'

	get 'control_proyecto' => 'transacciones#control_proyecto', :as => 'control_proyecto'

	get 'control_fecha' => 'transacciones#control_fecha', :as => 'control_fecha'

	root :to => "evento_publicos#index"

  get 'gestionar_concepto_gastos' => 'concepto_gastos#gestionar_concepto_gastos', :as => 'gestionar_concepto_gastos'

  get 'evaluar_presupuestos_pendientes' => 'presupuestos#evaluar_presupuestos_pendientes', :as => 'evaluar_presupuestos_pendientes'

  get 'presupuestos_evaluados' => 'presupuestos#presupuestos_evaluados', :as => 'presupuestos_evaluados'
  
  get 'gestionar_estados_presupuestos' => 'estado_presupuestos#gestionar_estados_presupuestos', :as => 'gestionar_estados_presupuestos'

  get 'evaluar_presupuesto/:id' => 'presupuestos#evaluar_presupuesto', :as => 'evaluar_presupuesto'

	get 'auditoria' => 'transacciones#auditoria', :as => 'auditoria'

	get 'reporte_voluntarios' => 'reporte_generados#reporte_voluntarios', :as => 'reporte_voluntarios'
	
	get 'reporte_proyectos' => 'reporte_generados#reporte_proyectos', :as => 'reporte_proyectos'

	get 'reporte_regionales' => 'reporte_generados#reporte_regionales', :as => 'reporte_regionales'

	get 'reporte_generado' => 'reporte_generados#reporte_generado', :as => 'reporte_generado'
	
	get 'reporte_new' => 'reporte_generados#reporte_new', :as => 'reporte_new'

	get 'usuario_bloqueado' => 'usuarios#usuario_bloqueado', :as => 'usuario_bloqueado'

      get 'gestionar_notificaciones' => 'notificacion_predeterminadas#gestionar_notificaciones', :as => 'gestionar_notificaciones'
	 get 'configuraciones_generales' => 'roles#configuraciones_generales', :as => 'configuraciones_generales'

  
  resources :ayudas
  

end

app/models/informe_gasto.rb
class InformeGasto < ActiveRecord::Base
  belongs_to :proyecto

  has_many :detalle_gastos
  has_many :concepto_gastos, :through => :detalle_gastos

  validates_presence_of :proyecto, message: " - es obligatorio"
 

end

app/controllers/informe_gastos_controller.rb
class InformeGastosController < ApplicationController
  before_action :set_informe_gasto, only: [:show, :edit, :update, :destroy, :gestionar_informe_gastos]

  # GET /informe_gastos
  # GET /informe_gastos.json
  def index
		authorize! :index, InformeGasto
    @informe_gastos = InformeGasto.all
  end

  # GET /informe_gastos/1
  # GET /informe_gastos/1.json
  def show
		raise CanCan::AccessDenied if !InformeGasto.accessible_by(current_ability, :show).include?(@informe_gasto) 
  end

  # GET /informe_gastos/new
  def new
		authorize! :new, InformeGasto
    @informe_gasto = InformeGasto.new
  end

  # GET /informe_gastos/1/edit
  def edit
		raise CanCan::AccessDenied if !InformeGasto.accessible_by(current_ability, :edit).include?(@informe_gasto) 
  end

  # POST /informe_gastos
  # POST /informe_gastos.json
  def create
		authorize! :create, InformeGasto
    @informe_gasto = InformeGasto.new(informe_gasto_params)

    respond_to do |format|
      if @informe_gasto.save
        sesion = Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)

        Transaccion.create!(descripcion: "Creacion del informe de gasto del proyecto #{@informe_gasto.proyecto.nombre}: #{@informe_gasto.attributes}",
                  sesion_id: sesion.id, 
                  proyecto_id: @informe_gasto.proyecto.id)

#         Transaccion.create!(
#           descripcion: "Creacion del informe de gasto del proyecto"+@informe_gasto.proyecto.nombre,
# ‪           sesion_id‬: sesion.id,
# ‪           proyecto_id‬: @informe_gasto.proyecto.id
#         )
        format.html { redirect_to gestionar_informe_gastos_path(@informe_gasto) }
        #format.html { redirect_to @informe_gasto, notice: 'Informe gasto fue creado satisfactoriamente.' }
        #format.json { render :show, status: :created, location: @informe_gasto }
      else
        format.html { render :back }
        #format.html { render :new }
        #format.json { render json: @informe_gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /informe_gastos/1
  # PATCH/PUT /informe_gastos/1.json
  def update
		raise CanCan::AccessDenied if !InformeGasto.accessible_by(current_ability, :update).include?(@informe_gasto) 
    respond_to do |format|
      if @informe_gasto.update(informe_gasto_params)
        sesion = Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)

        Transaccion.create!(descripcion: "Actualización del informe de gasto del proyecto #{@informe_gasto.proyecto.nombre}: #{@informe_gasto.previous_changes}",
                  sesion_id: sesion.id, 
                  proyecto_id: @informe_gasto.proyecto.id)

#         Transaccion.create!(
#           descripcion: 'Modificacion del informe de gasto del proyecto'+@informe_gasto.proyecto.nombre,
# ‪           sesion_id‬: sesion.id
# ‪           proyecto_id‬: @informe_gasto.proyecto.id
#         )
        format.html { redirect_to gestionar_informe_gastos_path(@informe_gasto) }
        #format.html { redirect_to @informe_gasto, notice: 'Informe gasto fue actualizado satisfactoriamente.' }
        #format.json { render :show, status: :ok, location: @informe_gasto }
      else
         format.html { render :back }
       #format.html { render :edit }
        #format.json { render json: @informe_gasto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /informe_gastos/1
  # DELETE /informe_gastos/1.json
  def destroy
		raise CanCan::AccessDenied if !InformeGasto.accessible_by(current_ability, :destroy).include?(@informe_gasto) 
    sesion = Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)

        Transaccion.create!(descripcion: "Eliminar el informe de gasto del proyecto #{@informe_gasto.proyecto.nombre}: #{@informe_gasto.attributes}",
                  sesion_id: sesion.id, 
                  proyecto_id: @informe_gasto.proyecto.id)

#         Transaccion.create!(
#           descripcion: 'Destruccion del informe de gasto del proyecto'+@informe_gasto.proyecto.nombre,
# ‪           sesion_id‬: sesion.id
# ‪           proyecto_id‬: @informe_gasto.proyecto.id
#         )
    @informe_gasto.destroy
    respond_to do |format|
      format.html { redirect_to informe_gastos_url, notice: 'Informe gasto fue borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end
  
  def gestionar_informe_gastos

    puts "************************ "
		raise CanCan::AccessDenied if !InformeGasto.accessible_by(current_ability, :gestionar_informe_gastos).include?(@informe_gasto) 
    #@detalles_gasto = DetalleGasto.where(informe_gasto_id: params[:id]).order(:monto).reverse_order
    #@detalles_gasto = @informe_gasto.detalle_gastos
    @proyecto = @informe_gasto.proyecto
    if @informe_gasto.detalle_gastos.nil? then
      @informe_gasto.montoTotal = 0
    else
      @informe_gasto.montoTotal = @informe_gasto.detalle_gastos.sum(:monto)
    end
    @conceptos_no_usados = ConceptoGasto.all - @informe_gasto.concepto_gastos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_informe_gasto
      @informe_gasto = InformeGasto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def informe_gasto_params
      params.permit(:montoTotal, :proyecto_id)
    end
end

app/helpers/informe_gastos_helper.rb
module InformeGastosHelper
end

app/views/informe_gastos/_form.html.erb
<%= form_for(@informe_gasto) do |f| %>
  <% if @informe_gasto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@informe_gasto.errors.count, "error") %> prohibited this informe_gasto from being saved:</h2>

      <ul>
      <% @informe_gasto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :montoTotal %><br>
    <%= f.text_field :montoTotal %>
  </div>
  <div class="field">
    <%= f.label :proyecto_id %><br>
    <%= f.text_field :proyecto_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/informe_gastos/edit.html.erb
<h1>Editing informe_gasto</h1>

<%= render 'form' %>

<%= link_to 'Ver', @informe_gasto %> |
<%= link_to 'Atrás', informe_gastos_path %>

app/views/informe_gastos/gestionar_informe_gastos.html.erb
<h1>Gestionar Informe de gastos <small>Administración de los gastos del proyecto</small></h1>
<ol class="breadcrumb">
  <li><i class="icon-dashboard"></i> Gestionar Informe de gastos</li>
  <li class="active"><i class="icon-file-alt"></i> Informe de gastos</li>
</ol>

<div class="row">
  <div class="col-lg-12">
      <label><h2> <%= @informe_gasto.proyecto.nombre %> </h2></label></br>
      <div class="form-group">
        <label>
          <% if @informe_gasto.proyecto.breveDescripcion.blank? then %>
            <h4> (No existe actualmente descripción del Proyecto) </h4>
          <% else %>
            <h4> <%= @informe_gasto.proyecto.breveDescripcion %> </h4>
          <% end %>
        </label>
        <p> <%#= @presupuesto.proyecto.breveDescripcion %> </p>
      </div>
    <!--</form>-->
    <! TODO Validar @detalles_presupuesto que no sea nil, si lo es hacer un camino separado y avisar > 
    <div class="form-group input-group">
      <span class="input-group-addon">
        Monto total acumulado  $
      </span>
      <input class="form-control" type="text" value=<%= number_with_precision(@informe_gasto.montoTotal, :precision => 2)  %> disabled="disabled"></input>
    </div>   
  <!</div>
  <br></br>
  <% if @informe_gasto.detalle_gastos.nil? then %>
    <h4> No existen gastos para este proyecto </h4>
  <% else %>
  <div class="col-lg-12 container">
    <ul id="pills" class="nav nav-pills nav-justified" data-tabs="pills" align="center">
      <li class="active">
        <a href="#lista" data-toggle="tab"><h4>Lista</h4></a>
      </li>
      <li>
        <a href="#paneles" data-toggle="tab"><h4>Paneles</h4></a>
      </li>
    </ul>
    <br></br>
    <div id="my-tab-content" class="tab-content">
      <div class="tab-pane" id="paneles">
        <% @informe_gasto.concepto_gastos.uniq.each do |concepto|%>
          <div class="col-lg-12">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <h3 class="panel-title"> <%= concepto.titulo %></h3>
              </div>
              <div class="panel-body">
                <div class="row">
                  <% sumatoria = 0 %>
                  <% @informe_gasto.detalle_gastos.uniq.each_with_index do |detalle, index|%>
                    <% if detalle.concepto_gasto_id == concepto.id then %>
                    <div class="col-lg-6">
                      <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title"> <%= detalle.titulo %> <!--<small> <td><%#= link_to '(Eliminar)', [@informe_gasto, detalle], method: :delete, data: { confirm: 'Esta seguro?' } %></td></small>-->
                          <!--<td> <%#= link_to '#', :class => "fa fa-trash-o" do %>
                            <i class="icon-remove"></i>
                          <%# end %> </i>
                        <i class="fa fa-trash-o"></i></td>-->
                        <small>
                                                      <% if !detalle.comprobante.nil? then %>
                                  
                                  <%= link_to content_tag(:i, fa_icon("file-text-o 2x", text: "")), comprobante_path(detalle.comprobante), method: :get, :style=>'padding-left: 6px;float:right', title: "Ver comprobante" %>
                                    <%#= link_to '(Ver comprobante)', comprobante_path(detalle.comprobante), method: :get %>
                            <% else %>

                                  <%= link_to content_tag(:i, fa_icon("paperclip 2x", text: "")), new_comprobante_path(:detalle_gasto_id => detalle.id), :style=>'padding-left: 6px;float:right', title: "Agregar comprobante" %>
                                    <%#= link_to '(Agregar comprobante)', new_comprobante_path(:detalle_gasto_id => detalle.id) %>  
                            <% end %>
                               <%= link_to content_tag(:i, fa_icon("trash 2x", text: "")), [@informe_gasto, detalle], method: :delete, data: { confirm: 'Esta seguro?' }, :style=>'padding-left: 6px;float:right', title: "Eliminar" %>
                                                    <%= link_to content_tag(:i, fa_icon("pencil-square-o 2x", text: "")), edit_detalle_gasto_path(detalle), :style=>'padding-left: 6px;float:right', title: "Editar" %>
                         
                                  <%#= link_to '(Editar)',  edit_detalle_gasto_path(detalle) %> 
                                  <%#= link_to '(X)', [@informe_gasto, detalle], method: :delete, data: { confirm: 'Esta seguro?' }%>
</small>
                          </h4> 
                        </div>
                        <div class="panel-body">
                          <label>Descripción del Gasto</label>
                          <p><%= detalle.descripcion %></li></p>
                          <label>Concepto (Rubro) del Gasto</label>
                          <p><%= detalle.concepto_gasto.titulo  %></li></p>
                          <label>Monto:</label>
                          <p>$ <%= number_with_precision(detalle.monto, :precision => 2) %></li></p>
                          <% sumatoria += detalle.monto %>
                        </div>
                      </div>
                    </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="panel-footer">
                Subtotal de <%= concepto.titulo %> = $ <%= number_with_precision(sumatoria, :precision => 2)  %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="tab-pane active" id="lista">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
          <% @informe_gasto.concepto_gastos.uniq.each do |concepto|%>
            <h3><%= concepto.titulo %></h3>
          <div class="table-responsive">
            <table class="table table-hover table-striped">
              <thead>
                <th>Descripción</th>
                <th>Monto</th>
                <th></th>
              </thead>
              <tbody>
                  <% sumatoria = 0 %>
                  <% @informe_gasto.detalle_gastos.uniq.each_with_index do |detalle, index|%>
                    <% if detalle.concepto_gasto_id == concepto.id then %>
                      <tr>
                        <td><%= detalle.titulo %></td>
                        <td>$ <%= number_with_precision(detalle.monto, :precision => 2) %></td>
                        <% sumatoria += detalle.monto %>
                        <td>
                          <small>
                            <%= link_to content_tag(:i, fa_icon("pencil-square-o 2x", text: "")), edit_detalle_gasto_path(detalle), title: "Editar" %>&nbsp;
                            <%= link_to content_tag(:i, fa_icon("trash 2x", text: "")), [@informe_gasto, detalle], method: :delete, data: { confirm: 'Esta seguro?' }, title: "Eliminar" %>&nbsp;
                                  <%#= link_to '(Editar)',  edit_detalle_gasto_path(detalle) %> 
                                  <%#= link_to '(X)', [@informe_gasto, detalle], method: :delete, data: { confirm: 'Esta seguro?' }%>
                            <% if !detalle.comprobante.nil? then %>
                                  <%= link_to content_tag(:i, fa_icon("file-text-o 2x", text: "")), comprobante_path(detalle.comprobante), method: :get, title: "Ver comprobante" %>
                                    <%#= link_to '(Ver comprobante)', comprobante_path(detalle.comprobante), method: :get %>
                            <% else %>
                                  <%= link_to content_tag(:i, fa_icon("paperclip 2x", text: "")), new_comprobante_path(:detalle_gasto_id => detalle.id), title: "Agregar comprobante" %>
                                    <%#= link_to '(Agregar comprobante)', new_comprobante_path(:detalle_gasto_id => detalle.id) %>  
                            <% end %>
                          </small>
                        </td>
                    <% end %>
                  <% end %>
                      <tr class="active">
                        <th>Subtotal de <%= concepto.titulo %></th>
                        <th> = $ <%= number_with_precision(sumatoria, :precision => 2)  %></th>
                        <td></td>
                      </tr>
                    </tbody>
                  </table>
                  <br></br>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-12">
      <div class="col-lg-3"></div>
      <div class="col-lg-6">
        <% if !@conceptos_no_usados.nil? then %>
          <div class="panel panel-info">
            <div class="panel-heading">
              <h4 class="panel-title">Concepto/s (Rubro/s) sin gastos:</h4>
            </div>
        <div class="panel-body">
          <% @conceptos_no_usados.each do |con| %>
            <label>- <%= con.titulo %></label></br>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br></br>
    <div class="col-lg-12 form-group input-group">
      <span class="input-group-addon">
          Monto total acumulado  $
      </span>
      <input class="form-control" type="text" value=<%= number_with_precision(@informe_gasto.montoTotal, :precision => 2)  %> disabled="disabled"></input>
    </div>
  <% end %>
    <div align="center">  
      <%= link_to "Agregar gasto", new_informe_gasto_detalle_gasto_path(@informe_gasto), class: "btn btn-primary btn-lg" %> 
    </div>
  </div>
</div>
</div>
        

    <!-- JavaScript -->
    
    

    <!-- Page Specific Plugins -->
    
    <!--
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    -->
     
   <script src="../../js/raphael-min.js"></script>
    
    <!--
   
    -->
    
    <script src="../../js/morris/chart-data-morris.js"></script>
    <script src="../../js/tablesorter/jquery.tablesorter.js"></script>
    <script src="../../js/tablesorter/tables.js"></script>

app/views/informe_gastos/index.html.erb
<h1>Listing informe_gastos</h1>

<table>
  <thead>
    <tr>
      <th>Montototal</th>
      <th>Proyecto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @informe_gastos.each do |informe_gasto| %>
      <tr>
        <td><%= informe_gasto.montoTotal %></td>
        <td><%= informe_gasto.proyecto %></td>
        <td><%= link_to 'Ver', informe_gasto %></td>
        <td><%= link_to 'Editar', edit_informe_gasto_path(informe_gasto) %></td>
        <td><%= link_to 'Borrar', informe_gasto, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Informe gasto', new_informe_gasto_path %>

app/views/informe_gastos/new.html.erb
<h1>Nuevo informe_gasto</h1>

<%= render 'form' %>

<%= link_to 'Atrás', informe_gastos_path %>

app/views/informe_gastos/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

<p>
  <strong>Montototal:</strong>
  <%= @informe_gasto.montoTotal %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= @informe_gasto.proyecto %>
</p>

<%= link_to 'Editar', edit_informe_gasto_path(@informe_gasto) %> |
<%= link_to 'Atrás', informe_gastos_path %>