config/routes.rb
Rails.application.routes.draw do

  resources :estado_academicos

  resources :regionales

	devise_for :usuarios, :controllers => {:registrations => "registrations"}

  resources :colaboradores

  resources :detalle_presupuestos#, only: [:index, :show, :edit, :update, :destroy]

  resources :historial_estado_presupuestos

  resources :presupuestos do
    resources :detalle_presupuestos#, only: [:new, :create]
  end

  resources :detalle_gastos

  resources :transacciones

  resources :sesiones

  resources :historial_estado_usuarios

  resources :asignacion_funciones

  resources :asistencia_eventos

  resources :asignacion_rol_predefinidos

  resources :privilegios

  resources :notificacion_sistemas

  resources :notificacion_emailes

  resources :notificaciones

  resources :evento_publicos

  resources :informe_gastos do
    resources :detalle_gastos #, only: [:new, :create]
  end

  resources :detalle_restricciones

  resources :restricciones

  resources :postulaciones do
	  member do
	    post 'aceptar'
	  end
  end

  resources :notas

  resources :asignacion_roles do
	resources :reportes
  end

  resources :roles

  

  resources :reportes

  resources :asignacion_actividades

  resources :requisitos

  resources :habilidades

  resources :notificacion_predeterminadas

  resources :historial_estado_actividades

  resources :actividades do
  	resources :historial_estado_actividades
  	resources :asignacion_actividades
  end

  resources :objetivo_especificos do
    resources :actividades
  end

  resources :objetivo_generales do
    resources :objetivo_especificos
  end

  resources :historial_estado_proyectos

  resources :proyectos do
	  member do
		  get :agregar_necesidad
	  end
    resources :asignacion_roles
    resources :notificacion_predeterminadas
    resources :historial_estado_proyectos

    get 'notificaciones_predeterminadas' => 'notificacion_predeterminadas#notificaciones_predeterminadas', :as => 'notificaciones_predeterminadas'

    resources :objetivo_generales
    resources :postulaciones
    resources :colaboradores

  end

  resources :necesidades

  resources :voluntarios do
    resources :experiencias 
    resources :horario_disponibles
    resources :notas
   
  end

  resources :horario_disponibles
  
  resources :experiencias
  

  
    get 'buscar_por_legajo/:legajo' => 'voluntarios#buscar_por_legajo'
    get 'buscar_usuario'=>'usuarios#buscar_usuario'
  
  
   get 'buscar_voluntario'=>'voluntarios#buscar_usuario'

  get 'cronograma_actividades'=>'actividades#cronograma_actividades'

  resources :usuarios do
      resources :notificacion_sistemas
  end

  resources :tipo_privilegios

  resources :concepto_gastos

  resources :estado_usuarios

  resources :estado_presupuestos

  resources :tipo_transacciones

  resources :comprobantes

  resources :organizacion_externas

  resources :tipo_roles

  resources :tipo_habilidades do
    resources :habilidades
  end

  resources :tipo_actividades

  resources :tipo_notificaciones

  resources :estvlado_actividades

  resources :tipo_proyectos

  resources :estado_proyectos
  get 'adminitrar_estado_usuario/'  => 'voluntarios#adminitrar_estado_usuario',:as => 'adminitrar_estado_usuario'
  get 'mis_notas/'  => 'voluntarios#mis_notas',:as => 'mis_notas'
  get 'Responder/' => 'notas#Responder',:as =>'Responder'
  get 'buscarusuario/'  => 'voluntarios#buscarusuario',:as => 'buscarusuario'
  get 'buscarusuario/'  => 'voluntarios#buscar_usuario'
  get 'dar_alta_voluntario' => 'usuarios#dar_alta_voluntario', :as => 'dar_alta_voluntario'

  get 'mis_proyectos', :as => 'proyectos/mis_proyectos', :controller => :proyectos
  get 'mis_necesidades', :as => 'necesidades/mis_necesidades', :controller => :necesidades
  
  get 'asignacion_actividad/busqueda_filtrada', :to => 'asignacion_actividades#busqueda_filtrada'

  get 'gestionar_experiencias/:id' => 'voluntarios#gestionar_experiencias', :as => 'gestionar_experiencias'

  get 'agregar_habilidad', :controller => :actividades
  get 'historial_estado_proyectos/modificar', to: 'historial_estado_proyectos#modificar'
  
  get 'usuarios_proyecto', :controller => :asignacion_roles
  
  get 'asignacion_actividad/dar_baja', to: 'asignacion_actividades#dar_baja'
  get 'asignacion_rol/dar_baja', to: 'asignacion_roles#dar_baja'

  get 'crear_organizacion_externa', :controller => :proyectos
  get 'gestionar_presupuesto/:id' => 'presupuestos#gestionar_presupuesto', :as => 'gestionar_presupuesto'
  get 'gestionar_informe_gastos/:id' => 'informe_gastos#gestionar_informe_gastos', :as => 'gestionar_informe_gastos'

  get 'gestionar_restricciones' => 'restricciones#gestionar_restricciones', :as => 'gestionar_restricciones'

  get 'horarios_disponibles/:id' => 'voluntarios#gestion_horarios_disponibles', :as => 'gestion_horarios_disponibles'
  get 'gestionar_nota_P/:id'  => 'voluntarios#gestionar_nota_P',:as => 'gestionar_nota_P'
  get 'gestionar_estado_usuario'=> 'voluntarios#gestionar_estado_usuario',:as =>'gestionar_estado_usuario'
 

  get 'gestionar_habilidades' => 'tipo_habilidades#gestionar_habilidades', :as => 'gestionar_habilidades'

	get 'control_usuario' => 'transacciones#control_usuario', :as => 'control_usuario'

	get 'control_proyecto' => 'transacciones#control_proyecto', :as => 'control_proyecto'

	get 'control_fecha' => 'transacciones#control_fecha', :as => 'control_fecha'

	root :to => "evento_publicos#index"

  get 'gestionar_concepto_gastos' => 'concepto_gastos#gestionar_concepto_gastos', :as => 'gestionar_concepto_gastos'

  get 'evaluar_presupuestos_pendientes' => 'presupuestos#evaluar_presupuestos_pendientes', :as => 'evaluar_presupuestos_pendientes'

  get 'presupuestos_evaluados' => 'presupuestos#presupuestos_evaluados', :as => 'presupuestos_evaluados'
  
  get 'gestionar_estados_presupuestos' => 'estado_presupuestos#gestionar_estados_presupuestos', :as => 'gestionar_estados_presupuestos'

  get 'evaluar_presupuesto/:id' => 'presupuestos#evaluar_presupuesto', :as => 'evaluar_presupuesto'

	get 'auditoria' => 'transacciones#auditoria', :as => 'auditoria'

	get 'reporte_voluntarios' => 'reporte_generados#reporte_voluntarios', :as => 'reporte_voluntarios'
	
	get 'reporte_proyectos' => 'reporte_generados#reporte_proyectos', :as => 'reporte_proyectos'

	get 'reporte_regionales' => 'reporte_generados#reporte_regionales', :as => 'reporte_regionales'

	get 'reporte_generado' => 'reporte_generados#reporte_generado', :as => 'reporte_generado'
	
	get 'reporte_new' => 'reporte_generados#reporte_new', :as => 'reporte_new'

	get 'usuario_bloqueado' => 'usuarios#usuario_bloqueado', :as => 'usuario_bloqueado'

      get 'gestionar_notificaciones' => 'notificacion_predeterminadas#gestionar_notificaciones', :as => 'gestionar_notificaciones'
	 get 'configuraciones_generales' => 'roles#configuraciones_generales', :as => 'configuraciones_generales'

  
  resources :ayudas
  

end

app/models/notificacion_predeterminada.rb
class NotificacionPredeterminada < ActiveRecord::Base
  belongs_to :proyecto
  belongs_to :tipo_notificacion

  validates :tipo_notificacion, uniqueness: {
    scope: :proyecto,
    message: '- No pueden existir dos Notificaciones Predeterminadas para el mismo proyecto' }

end

app/controllers/notificacion_predeterminadas_controller.rb
class NotificacionPredeterminadasController < ApplicationController
  before_action :set_notificacion_predeterminada, only: [:show, :edit, :update, :destroy]
  before_action :set_proyecto, only: [:index, :new, :create, :notificaciones_predeterminadas]

  # GET /notificacion_predeterminadas
  # GET /notificacion_predeterminadas.json
  def index
		#authorize! :index, NotificacionPredeterminada
    #@notificacion_predeterminadas = NotificacionPredeterminada.all
    @notificacion_predeterminadas = @proyecto.notificacion_predeterminadas
  end

  # GET /notificacion_predeterminadas/1
  # GET /notificacion_predeterminadas/1.json
  def show
		#authorize! :show, NotificacionPredeterminada
  end

  # GET /notificacion_predeterminadas/new
  def new
		authorize! :new, NotificacionPredeterminada
    #@notificacion_predeterminada = NotificacionPredeterminada.new
    @notificacion_predeterminada = @proyecto.notificacion_predeterminadas.new
    
  end

  # GET /notificacion_predeterminadas/1/edit
  def edit
		authorize! :edit, NotificacionPredeterminada
  end

  # POST /notificacion_predeterminadas
  # POST /notificacion_predeterminadas.json
  def create
		#authorize! :create, NotificacionPredeterminada
    #@notificacion_predeterminada = NotificacionPredeterminada.new(notificacion_predeterminada_params)
    @notificacion_predeterminada = @proyecto.notificacion_predeterminadas.new(notificacion_predeterminada_params)

    respond_to do |format|
      if @notificacion_predeterminada.save
        format.html { redirect_to :back}#@notificacion_predeterminada, notice: 'Notificacion predeterminada fue creado satisfactoriamente.' }
        #format.json { render :back}#, status: :created, location: @notificacion_predeterminada }
      else
        format.html { render :back }
        format.json { render json: @notificacion_predeterminada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notificacion_predeterminadas/1
  # PATCH/PUT /notificacion_predeterminadas/1.json
  def update
		authorize! :update, NotificacionPredeterminada
    respond_to do |format|
      if @notificacion_predeterminada.update(notificacion_predeterminada_params)
        format.html { redirect_to @notificacion_predeterminada, notice: 'Notificacion predeterminada fue actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @notificacion_predeterminada }
      else
        format.html { render :edit }
        format.json { render json: @notificacion_predeterminada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notificacion_predeterminadas/1
  # DELETE /notificacion_predeterminadas/1.json
  def destroy
		#authorize! :destroy, NotificacionPredeterminada
    @notificacion_predeterminada.destroy
    respond_to do |format|
      format.html { redirect_to :back}#, notice: 'Notificacion predeterminada fue borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end
  
  def gestionar_notificaciones

		  #authorize! :gestionar_notificaciones, NotificacionPredeterminada
    #@proyectos = Proyecto.where(id: AsignacionRol.find_by(usuario_id: current_usuario.id, esActual: true, rol_id: Rol.find_by(nombre: 'Director').id).proyecto_id)

		#authorize! :gestionar_notificaciones, NotificacionPredeterminada
    #asignaciones = 
    #@proyectos = Proyecto.joins(asignacion_roles: {:rol}).where('asignacion_roles.usuario_id =? AND (asignacion_roles.rol.nombre =? OR asignacion_roles.rol.nombre =?)', current_usuario, 'Director', 'Coordinador').uniq
    #@proyectos = Proyecto.joins(asignacion_roles: :rol).where('asignacion_roles.usuario_id =? AND (asignacion_roles.rol.nombre =? OR asignacion_roles.rol.nombre =?)', current_usuario, 'Director', 'Coordinador').uniq
    #@proyectos = Proyecto.includes(asignacion_roles: :rol).where(asignacion_rol: {usuario_id: current_usuario}, rol: {nombre: 'Director'})
    #@asignaciones = AsignacionRol.find_by(usuario: current_usuario, esActual: true, active: true, rol_id: Rol.find_by('nombre = ?','Coordinador'))
   #if !@asignaciones.blank?
    #  @asignaciones do |asignacion|
    #    @proyectos = @proyectos + asignacion.proyecto
#
    #  end 
    #end
    @proyectos = []
    @asignaciones = AsignacionRol.find_by(usuario_id: current_usuario.id, esActual: true, active: true, rol_id: Rol.find_by('nombre = ?','Director').id)
    if !@asignaciones.blank?
      [*@asignaciones].each do |asignacion|
        @proyectos = @proyectos + Proyecto.where(id: asignacion.proyecto_id)
      end
    end
    @asignaciones = AsignacionRol.find_by(usuario_id: current_usuario.id, esActual: true, active: true, rol_id: Rol.find_by('nombre = ?','Coordinador').id)
    if !@asignaciones.blank?
      [*@asignaciones].each do |asignacion|
        @proyectos = @proyectos + Proyecto.where(id: asignacion.proyecto_id)
      end
    end
    #@proyectos = Proyecto.where(id: AsignacionRol.find_by(usuario_id: current_usuario.id, esActual: true, active: true, rol_id: Rol.find_by('nombre = ?','Coordinador').id).proyecto_id)
  end

  def notificaciones_predeterminadas 
		#authorize! :notificaciones_predeterminadas, NotificacionPredeterminada
    @notificaciones_no_usadas = TipoNotificacion.all - @proyecto.tipo_notificaciones   #resto las listas
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notificacion_predeterminada
      @notificacion_predeterminada = NotificacionPredeterminada.find(params[:id])
    end

    def set_proyecto
      @proyecto = Proyecto.find params[:proyecto_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notificacion_predeterminada_params
      params.permit(:proyecto_id, :tipo_notificacion_id)
    end
end

app/helpers/notificacion_predeterminadas_helper.rb
module NotificacionPredeterminadasHelper
end

app/views/notificacion_predeterminadas/_form.html.erb
<%= form_for(@notificacion_predeterminada) do |f| %>
  <% if @notificacion_predeterminada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notificacion_predeterminada.errors.count, "error") %> prohibited this notificacion_predeterminada from being saved:</h2>

      <ul>
      <% @notificacion_predeterminada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proyecto_id %><br>
    <%= f.text_field :proyecto_id %>
  </div>
  <div class="field">
    <%= f.label :tipo_notificacion_id %><br>
    <%= f.text_field :tipo_notificacion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notificacion_predeterminadas/edit.html.erb
<h1>Editing notificacion_predeterminada</h1>

<%= render 'form' %>

<%= link_to 'Ver', @notificacion_predeterminada %> |
<%= link_to 'Atrás', notificacion_predeterminadas_path %>

app/views/notificacion_predeterminadas/gestionar_notificaciones.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

<h1>Metodos de Notificación <small>Administración de los métodos de notificación del proyecto</small></h1>
<ol class="breadcrumb">
  <li><i class="icon-dashboard"></i> Configuraciones</li>
  <li class="active"><i class="icon-file-alt"></i> Proyectos actuales</li>
</ol>


<% if not @proyectos.blank? %>

<div class="row">
  <div class="col-lg-12">
    <% if @proyectos.empty? then %>
      <h3>Actualmente no tiene proyectos a cargo</h3> 
      <% else %>
          <% @proyectos.each do |proyecto| %>
          <div class="col-lg-6">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h4 class="panel-title"> 
                      <%= link_to proyecto.nombre, proyecto_path(proyecto), method: :get %> 
                    </h4> 
                  </div>
                  <div class="panel-body">
                    <h4> Descripción: </h4>
                    <p> <%= proyecto.breveDescripcion %> </p>
                    <div align="center">
                        <%= link_to "Gestionar métodos de notificación", proyecto_notificaciones_predeterminadas_path(proyecto.id), :class => "btn btn-default" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
    <% end %>
  </div>
</div> 

<% else  %>

Usted no es director de ningún proyecto actualmente.

<% end %>

<div align="center"><%= link_to 'Atrás', :back, :class => "btn btn-default btn-lg" %></div>
    <!-- JavaScript -->
    
    

    <!-- Page Specific Plugins -->
    
    <!--
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    -->
     

app/views/notificacion_predeterminadas/index.html.erb
<h1>Listing notificacion_predeterminadas</h1>

<table>
  <thead>
    <tr>
      <th>Proyecto</th>
      <th>Tipo notificacion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notificacion_predeterminadas.each do |notificacion_predeterminada| %>
      <tr>
        <td><%= notificacion_predeterminada.proyecto %></td>
        <td><%= notificacion_predeterminada.tipo_notificacion %></td>
        <td><%= link_to 'Ver', notificacion_predeterminada %></td>
        <td><%= link_to 'Editar', edit_notificacion_predeterminada_path(notificacion_predeterminada) %></td>
        <td><%= link_to 'Borrar', notificacion_predeterminada, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Notificacion predeterminada', new_notificacion_predeterminada_path %>

app/views/notificacion_predeterminadas/new.html.erb
<h1>Nuevo notificacion_predeterminada</h1>

<%= render 'form' %>

<%= link_to 'Atrás', notificacion_predeterminadas_path %>

app/views/notificacion_predeterminadas/notificaciones_predeterminadas.html.erb
<h1>Metodos de Notificación <small>Administración de los tipos de notificación del proyecto</small></h1>
<ol class="breadcrumb">
  <li><i class="icon-dashboard"></i> Configuraciones</li>
  <li class="active"><i class="icon-file-alt"></i> Notificaciones predeterminadas</li>
</ol>
<br></br>
<div class="row">
  <div class="col-lg-12">
    <% if !@proyecto.notificacion_predeterminadas.nil? then %>       
      <% @proyecto.notificacion_predeterminadas.each do |np| #recorro las notificaciones del proyecto (usadas) %>
        <div class="col-lg-6">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title"> 
                <%= np.tipo_notificacion.nombre %>              
              </h3>
            </div>
            <div class="panel-body">
              <div class="row" align="center">
                <%= link_to 'Desactivar', 
                  notificacion_predeterminada_path(np), # boton verde para eliminar la notificacion predeterminada
                  class: "btn btn-success btn-lg", 
                  data: { method: :delete } %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <% if !@notificaciones_no_usadas.nil? then %>
      <% @notificaciones_no_usadas.each do |_tipo_notificacion| #recorro las notificaciones no usadas por el proyecto %>
        <div class="col-lg-6">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title"> 
                <%= _tipo_notificacion.nombre %>
              </h3>
            </div>
            <div class="panel-body">
              <div class="row" align="center">
                <%= link_to 'Activar', 
                  notificacion_predeterminadas_path(proyecto_id: @proyecto.id, tipo_notificacion_id: _tipo_notificacion.id), 
                  class: "btn btn-default btn-lg",          # boton gris para crear la notificacion predeterminada
                  data: { method: :post } %>                
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<div align="center"><%= link_to 'Cancelar', :back, :class => "btn btn-default btn-lg" %></div>
</div>
        

    <!-- JavaScript -->
    
    

    <!-- Page Specific Plugins -->
    
    <!--
    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    -->
     
 
    
    

app/views/notificacion_predeterminadas/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

<p>
  <strong>Proyecto:</strong>
  <%= @notificacion_predeterminada.proyecto %>
</p>

<p>
  <strong>Tipo notificacion:</strong>
  <%= @notificacion_predeterminada.tipo_notificacion %>
</p>

<%= link_to 'Editar', edit_notificacion_predeterminada_path(@notificacion_predeterminada) %> |
<%= link_to 'Atrás', notificacion_predeterminadas_path %>