config/routes.rb
Rails.application.routes.draw do

  resources :estado_academicos

  resources :regionales

	devise_for :usuarios, :controllers => {:registrations => "registrations"}

  resources :colaboradores

  resources :detalle_presupuestos#, only: [:index, :show, :edit, :update, :destroy]

  resources :historial_estado_presupuestos

  resources :presupuestos do
    resources :detalle_presupuestos#, only: [:new, :create]
  end

  resources :detalle_gastos

  resources :transacciones

  resources :sesiones

  resources :historial_estado_usuarios

  resources :asignacion_funciones

  resources :asistencia_eventos

  resources :asignacion_rol_predefinidos

  resources :privilegios

  resources :notificacion_sistemas

  resources :notificacion_emailes

  resources :notificaciones

  resources :evento_publicos

  resources :informe_gastos do
    resources :detalle_gastos #, only: [:new, :create]
  end

  resources :detalle_restricciones

  resources :restricciones

  resources :postulaciones do
	  member do
	    post 'aceptar'
	  end
  end

  resources :notas

  resources :asignacion_roles do
	resources :reportes
  end

  resources :roles

  

  resources :reportes

  resources :asignacion_actividades

  resources :requisitos

  resources :habilidades

  resources :notificacion_predeterminadas

  resources :historial_estado_actividades

  resources :actividades do
  	resources :historial_estado_actividades
  	resources :asignacion_actividades
  end

  resources :objetivo_especificos do
    resources :actividades
  end

  resources :objetivo_generales do
    resources :objetivo_especificos
  end

  resources :historial_estado_proyectos

  resources :proyectos do
	  member do
		  get :agregar_necesidad
	  end
    resources :asignacion_roles
    resources :notificacion_predeterminadas
    resources :historial_estado_proyectos

    get 'notificaciones_predeterminadas' => 'notificacion_predeterminadas#notificaciones_predeterminadas', :as => 'notificaciones_predeterminadas'

    resources :objetivo_generales
    resources :postulaciones
    resources :colaboradores

  end

  resources :necesidades

  resources :voluntarios do
    resources :experiencias 
    resources :horario_disponibles
    resources :notas
   
  end

  resources :horario_disponibles
  
  resources :experiencias
  

  
    get 'buscar_por_legajo/:legajo' => 'voluntarios#buscar_por_legajo'
    get 'buscar_usuario'=>'usuarios#buscar_usuario'
  
  
   get 'buscar_voluntario'=>'voluntarios#buscar_usuario'

  get 'cronograma_actividades'=>'actividades#cronograma_actividades'

  resources :usuarios do
      resources :notificacion_sistemas
  end

  resources :tipo_privilegios

  resources :concepto_gastos

  resources :estado_usuarios

  resources :estado_presupuestos

  resources :tipo_transacciones

  resources :comprobantes

  resources :organizacion_externas

  resources :tipo_roles

  resources :tipo_habilidades do
    resources :habilidades
  end

  resources :tipo_actividades

  resources :tipo_notificaciones

  resources :estvlado_actividades

  resources :tipo_proyectos

  resources :estado_proyectos
  get 'adminitrar_estado_usuario/'  => 'voluntarios#adminitrar_estado_usuario',:as => 'adminitrar_estado_usuario'
  get 'mis_notas/'  => 'voluntarios#mis_notas',:as => 'mis_notas'
  get 'Responder/' => 'notas#Responder',:as =>'Responder'
  get 'buscarusuario/'  => 'voluntarios#buscarusuario',:as => 'buscarusuario'
  get 'buscarusuario/'  => 'voluntarios#buscar_usuario'
  get 'dar_alta_voluntario' => 'usuarios#dar_alta_voluntario', :as => 'dar_alta_voluntario'

  get 'mis_proyectos', :as => 'proyectos/mis_proyectos', :controller => :proyectos
  get 'mis_necesidades', :as => 'necesidades/mis_necesidades', :controller => :necesidades
  
  get 'asignacion_actividad/busqueda_filtrada', :to => 'asignacion_actividades#busqueda_filtrada'

  get 'gestionar_experiencias/:id' => 'voluntarios#gestionar_experiencias', :as => 'gestionar_experiencias'

  get 'agregar_habilidad', :controller => :actividades
  get 'historial_estado_proyectos/modificar', to: 'historial_estado_proyectos#modificar'
  
  get 'usuarios_proyecto', :controller => :asignacion_roles
  
  get 'asignacion_actividad/dar_baja', to: 'asignacion_actividades#dar_baja'
  get 'asignacion_rol/dar_baja', to: 'asignacion_roles#dar_baja'

  get 'crear_organizacion_externa', :controller => :proyectos
  get 'gestionar_presupuesto/:id' => 'presupuestos#gestionar_presupuesto', :as => 'gestionar_presupuesto'
  get 'gestionar_informe_gastos/:id' => 'informe_gastos#gestionar_informe_gastos', :as => 'gestionar_informe_gastos'

  get 'gestionar_restricciones' => 'restricciones#gestionar_restricciones', :as => 'gestionar_restricciones'

  get 'horarios_disponibles/:id' => 'voluntarios#gestion_horarios_disponibles', :as => 'gestion_horarios_disponibles'
  get 'gestionar_nota_P/:id'  => 'voluntarios#gestionar_nota_P',:as => 'gestionar_nota_P'
  get 'gestionar_estado_usuario'=> 'voluntarios#gestionar_estado_usuario',:as =>'gestionar_estado_usuario'
 

  get 'gestionar_habilidades' => 'tipo_habilidades#gestionar_habilidades', :as => 'gestionar_habilidades'

	get 'control_usuario' => 'transacciones#control_usuario', :as => 'control_usuario'

	get 'control_proyecto' => 'transacciones#control_proyecto', :as => 'control_proyecto'

	get 'control_fecha' => 'transacciones#control_fecha', :as => 'control_fecha'

	root :to => "evento_publicos#index"

  get 'gestionar_concepto_gastos' => 'concepto_gastos#gestionar_concepto_gastos', :as => 'gestionar_concepto_gastos'

  get 'evaluar_presupuestos_pendientes' => 'presupuestos#evaluar_presupuestos_pendientes', :as => 'evaluar_presupuestos_pendientes'

  get 'presupuestos_evaluados' => 'presupuestos#presupuestos_evaluados', :as => 'presupuestos_evaluados'
  
  get 'gestionar_estados_presupuestos' => 'estado_presupuestos#gestionar_estados_presupuestos', :as => 'gestionar_estados_presupuestos'

  get 'evaluar_presupuesto/:id' => 'presupuestos#evaluar_presupuesto', :as => 'evaluar_presupuesto'

	get 'auditoria' => 'transacciones#auditoria', :as => 'auditoria'

	get 'reporte_voluntarios' => 'reporte_generados#reporte_voluntarios', :as => 'reporte_voluntarios'
	
	get 'reporte_proyectos' => 'reporte_generados#reporte_proyectos', :as => 'reporte_proyectos'

	get 'reporte_regionales' => 'reporte_generados#reporte_regionales', :as => 'reporte_regionales'

	get 'reporte_generado' => 'reporte_generados#reporte_generado', :as => 'reporte_generado'
	
	get 'reporte_new' => 'reporte_generados#reporte_new', :as => 'reporte_new'

	get 'usuario_bloqueado' => 'usuarios#usuario_bloqueado', :as => 'usuario_bloqueado'

      get 'gestionar_notificaciones' => 'notificacion_predeterminadas#gestionar_notificaciones', :as => 'gestionar_notificaciones'
	 get 'configuraciones_generales' => 'roles#configuraciones_generales', :as => 'configuraciones_generales'

  
  resources :ayudas
  

end

app/controllers/asignacion_actividades_controller.rb
class AsignacionActividadesController < ApplicationController
  before_action :set_asignacion_actividad, only: [:show, :edit, :update, :destroy]


  # GET /asignacion_actividades
  # GET /asignacion_actividades.json
  def index
		
	  @actividad = Actividad.find(params[:actividad_id])
		
	  @asignacion_actividades = @actividad.asignacion_actividades

	  #@asignacion_actividades = AsignacionActividad.where('actividad_id =?', @actividad.id ) 
	  @proyecto = @actividad.proyecto
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :index).include?(@asignacion_actividades.first)
		else
			authorize! :index, AsignacionActividad
		end
  end

  # GET /asignacion_actividades/1
  # GET /asignacion_actividades/1.json
  def show
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @asignacion_actividad.actividad.proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @asignacion_actividad.actividad.proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :show).include?(@asignacion_actividad)
		else
			authorize! :show, AsignacionActividad
		end
  end

  # GET /asignacion_actividades/new
  def new
		 @actividad = Actividad.find(params[:actividad_id])
		@proyecto = @actividad.proyecto
    
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :new).include?(@actividad.asignacion_actividades.first)
		else
			authorize! :new, AsignacionActividad
		end
	 
			@asignacion_actividad = AsignacionActividad.new
	
  end

  # GET /asignacion_actividades/1/edit
  def edit
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @asignacion_actividad.actividad.proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @asignacion_actividad.actividad.proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :edit).include?(@asignacion_actividad)
		else
			authorize! :edit, AsignacionActividad
		end
  end

  # POST /asignacion_actividades
  # POST /asignacion_actividades.json
  def create
		
		@actividad = Actividad.find(params[:asignacion_actividad][:actividad_id])
  	@proyecto = @actividad.proyecto
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :create).include?(@actividad.asignacion_actividades.first)
		else
			authorize! :create, AsignacionActividad
		end
  	if params[:asignacion_actividad][:usuario_id].to_s.blank? #(!defined? (params[:usuario_id])) && (defined? params[:usuario])
      p "VACIOOO"

  		@asignacion_actividad= AsignacionActividad.new
      @usuarios = Usuario.page(params[:page]).search query: params[:asignacion_actividad][:usuario]
  		respond_to do |format|
  			format.html { render '/asignacion_actividades/busqueda_filtrada', :actividad_id => @actividad.id, :usuario => params[:usuario] }
      end
  	else
  		p "NOOO VACIOOO"
      #aca agregar revision asignacion proyecto
      if en_proyecto(params[:asignacion_actividad][:usuario_id], @proyecto.id)
        @asignacion_actividad = AsignacionActividad.new(actividad_id: params[:asignacion_actividad][:actividad_id], usuario_id: params[:asignacion_actividad][:usuario_id])
    		@asignacion_actividad.vigente = true
        if unica(@asignacion_actividad.usuario_id,@asignacion_actividad.actividad_id) == true

    	    respond_to do |format|
      	    if  @asignacion_actividad.save
      	      format.html { redirect_to :controller => 'asignacion_actividades', :action => 'index', :actividad_id => @asignacion_actividad.actividad.id
      		      flash[:success] = 'Asignacion actividad fue creado satisfactoriamente.' }
      	      format.json { render :show, status: :created, location: @asignacion_actividad }
      	    else
      				format.html { render :new }
      				format.json { render json: @asignacion_actividad.errors, status: :unprocessable_entity }
      	    end
          end    
    		else
    	    respond_to do |format|
    		    format.html { redirect_to :controller => 'asignacion_actividades', :action => 'index', :actividad_id => @asignacion_actividad.actividad.id
    		             flash[:danger] = 'El usuario ya se encuentra asignado' } 
          end
    		end
      else 
        respond_to do |format|
            format.html { redirect_to :controller => 'asignacion_actividades', :action => 'index', :actividad_id => params[:asignacion_actividad][:actividad_id]
                     flash[:danger] = 'El usuario no se encuentra asignado al Proyecto' } 
        end  
      end 
  	end
  end

  # PATCH/PUT /asignacion_actividades/1
  # PATCH/PUT /asignacion_actividades/1.json
  def update
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @asignacion_actividad.actividad.proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @asignacion_actividad.actividad.proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :update).include?(@asignacion_actividad)
		else
			authorize! :update, AsignacionActividad
		end
    respond_to do |format|
      if @asignacion_actividad.update(asignacion_actividad_params)
        format.html { redirect_to @asignacion_actividad
          flash[:success] = 'Asignacion actividad fue actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @asignacion_actividad }
      else
        format.html { render :edit }
        format.json { render json: @asignacion_actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  def dar_baja
    @asignacion_actividad = AsignacionActividad.find(params[:id])
		raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :dar_baja).include?(@asignacion_actividad) 
    @asignacion_actividad.vigente = false
    respond_to do |format|
      if @asignacion_actividad.save
	      format.html { redirect_to :controller => 'asignacion_actividades', :action => 'index', :actividad_id => @asignacion_actividad.actividad.id
		     flash[:success] = 'La asignación fue dada de baja satisfactoriamente.' }
        format.json { render :show, status: :created, location: @asignacion_actividad }
      end
    end
  end

  # DELETE /asignacion_actividades/1
  # DELETE /asignacion_actividades/1.json
  def destroy
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @asignacion_actividad.actividad.proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @asignacion_actividad.actividad.proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :destroy).include?(@asignacion_actividad)
		else
			authorize! :destroy, AsignacionActividad
		end
    @actividad_id = @asignacion_actividad.actividad_id
    @asignacion_actividad.destroy
    respond_to do |format|
	      format.html { redirect_to :controller => 'asignacion_actividades', :action => 'index', :actividad_id => @actividad_id
		      flash[:success] = 'Asignacion actividad fue borrado satisfactoriamente.' }
      format.html { redirect_to asignacion_actividades_url
       flash[:success] = 'Asignacion actividad fue borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  def unica( usuario, actividad) 
  	if AsignacionActividad.all.where(usuario_id: usuario, actividad_id: actividad,vigente: true ).count == 0
  		#p true
  		true
  	else
  		#p false
  		false
  	end
  end

  def en_proyecto( usuario, proyecto)
    #oras += Actividad.where("id = ? AND fechaRealInicio BETWEEN ? AND ? ", asig.actividad_id, inicio, fin).duracionReal
    #if (AsignacionRol.all.where(usuario_id: usuario, proyecto_id: proyecto).count == 0)
    if (AsignacionRol.all.where(usuario_id: usuario, proyecto_id: proyecto, active: true, esActual: true).count == 0)
      false
    else
      true
    end
  end


  def busqueda_filtrada
       @asignacion_actividad = AsignacionActividad.find(params[:id])
				if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @asignacion_actividad.actividad.proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @asignacion_actividad.actividad.proyecto).count == 1
			raise CanCan::AccessDenied if !AsignacionActividad.accessible_by(current_ability, :busqueda_filtrada).include?(@asignacion_actividad)
		else
			authorize! :busqueda_filtrada, AsignacionActividad
		end
       @usuarios = Usuario.page(params[:page]).search query: params[:usuario]
	
  end

  def busqueda_por_habilidad
      @actividad = Actividad.find(params[:actividad_id])
      @requisito = Requisito.new
      
      if !params[:requisito][:habilidad].to_s.blank?
          

      else

	      redirect_to 'busqueda_por_habilidad', :actividad_id => @actividad.id



      end
  	
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignacion_actividad
      @asignacion_actividad = AsignacionActividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignacion_actividad_params

app/helpers/asignacion_actividades_helper.rb
module AsignacionActividadesHelper
end

app/views/asignacion_actividades/_form.html.erb
<%= simple_form_for(@asignacion_actividad) do |f| %>
  <% if @asignacion_actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignacion_actividad.errors.count, "error") %> prohibited this asignacion_actividad from being saved:</h2>

      <ul>
      <% @asignacion_actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :actividad_id ,:as => :hidden, input_html: {value: @actividad.id}  %>

<div class="form-group input-group">
                <span class="input-group-addon">@</span>              
   <%= f.input :usuario, as: :autocomplete, label: false, url: usuarios_proyecto_path, input_html: { autofocus: true  }  %>
   </div>
   
 <div class="modal-footer">
	 <%= f.button :submit, :class => 'btn btn-primary', :value => 'Confirmar' %>
 </div>

<% end %>

app/views/asignacion_actividades/busqueda_filtrada.html.erb
<%= simple_form_for(@asignacion_actividad) do |f| %>
  <% if @asignacion_actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignacion_actividad.errors.count, "error") %> prohibited this asignacion_actividad from being saved:</h2>

      <ul>
      <% @asignacion_actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :actividad_id ,:as => :hidden, input_html: {value: @actividad.id}  %>

<div class="form-group input-group">
                <span class="input-group-addon">@</span>              
   <%= f.input :usuario_id, label: false, :collection => @usuarios%>
   </div>
   
 <div class="modal-footer">
	 <%= f.button :submit, :class => 'btn btn-primary', :value => 'Confirmar' %>
	 <%= link_to 'Atrás', :back %>
 </div>

<% end %>



<h1>Lista de Usuarios</h1>

<table class="table table-hover table-striped tablesorter">
  <thead>
    <tr>
      <th>Foto</th>
      <th>Nombre de Usuario   </th>
      <th>Apellido y Nombre   </th>
      <th>Email   </th>
      <th>Habilidades   </th>
      <th>Estado Académico </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
      <td><%= image_tag usuario.foto.url(:thumb) %></td>
        <td><%= usuario.nombreUsuario %></td>

        <td><%= usuario.apellido_nombre %></td>
        <td><%= usuario.email %></td>
        
        <td>
        
				  <% if usuario.type == "Voluntario"%>
			         
			         <% usuario.experiencias.each do |experiencia| %>
			         | <%= experiencia.habilidad %> | <br>
			         
			         <% end %>	  
				  <% else %>
				     No posee habilidades cargadas
				  <% end %>
				  

      

        
	</td>
	<td>
		<%= link_to 'Ver Estado Académico', estado_academicos_path(:usuario_id => usuario.id), remote: true, data: { target: 'modal', modal: true } %> 
	</td>
        
    <% end %>
      </tr> 
      
  </tbody>
</table>

<br>

app/views/asignacion_actividades/edit.html.erb
<h1>Editar Asignación de Recursos a la Actividad</h1>

<%= render 'form' %>

<%= link_to 'Ver', @asignacion_actividad %> |
<%= link_to 'Atrás', asignacion_actividades_path %>

app/views/asignacion_actividades/index.html.erb
<h1>Lista Recursos Asignados a la Actividad</h1>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

         <table class="table table-hover table-striped tablesorter">
                <thead>
                  <tr>
                    <th class="col-lg-3">Apellido y Nombre</th>
                    <th class="col-lg-2">Fecha Asignación </th>
                    <th class="col-lg-2">Ultima Fecha Cambio </th>
                    <th class="col-lg-3">Vigente</th>
                    <th class="col-lg-3">Acciones</th>
                    <th class="col-lg-3"></th>
                    <th></th>
                  </tr>
                </thead>

                <tbody>           
                    <% @asignacion_actividades.each do |asignacion| %>
                    <% if asignacion.es_vigente == "Si" %>
                    <tr style="color: black">
                    <%else %>
                    <tr style="font-style: italic">
                    <% end %>
                        <td><%= asignacion.usuario %></td>
                        <td><%= asignacion.created_at.to_formatted_s(:long_ordinal)%></td>
                        <td><%= asignacion.updated_at.to_formatted_s(:long_ordinal)%></td>
                        <td><%= asignacion.es_vigente %></td>
                        <td>
                        <% if asignacion.es_vigente == "No" %>
                          Dar Baja </td>
                        <% else %>
                          <%= link_to 'Dar Baja', asignacion_actividad_dar_baja_path(:id => asignacion.id), data: {confirm: 'Seguro?'} %> 
                        <% end %>
                         
                         <%#= | link_to 'Borrar', asignacion, method: :delete, data: { confirm: 'Seguro?' } %> </td>
                        <td>
                        </td>
                        <td>
                             <i class="fa fa-minus"></i>
		    </tr>
		    </div>
                    <% end %>
 </tbody>
</table>
<% if @asignacion_actividades.empty? then %>
  <p>
    No se encuentra asignado ningun Usuario.
  </p>
<% end %>

<%= link_to '+', new_asignacion_actividad_path(:actividad_id => @actividad.id) , :class => "classbtn btn-primary btn-sm" %> | 
<%= link_to 'Atrás', @actividad %>

app/views/asignacion_actividades/new.html.erb
<h1>Agregar un Recurso a la Actividad</h1>

<%= render 'form' %>

<%= link_to 'Atrás', asignacion_actividades_path(:actividad_id => @actividad.id)%>

app/views/asignacion_actividades/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

<p>
  <strong>Vigente:</strong>
  <%= @asignacion_actividad.vigente %>
</p>

<p>
  <strong>Actividad:</strong>
  <%= @asignacion_actividad.actividad %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @asignacion_actividad.usuario %>
</p>

<%= link_to 'Editar', edit_asignacion_actividad_path(@asignacion_actividad) %> |
<%= link_to 'Atrás', asignacion_actividades_path %>