config/routes.rb
Rails.application.routes.draw do

  resources :estado_academicos

  resources :regionales

	devise_for :usuarios, :controllers => {:registrations => "registrations"}

  resources :colaboradores

  resources :detalle_presupuestos#, only: [:index, :show, :edit, :update, :destroy]

  resources :historial_estado_presupuestos

  resources :presupuestos do
    resources :detalle_presupuestos#, only: [:new, :create]
  end

  resources :detalle_gastos

  resources :transacciones

  resources :sesiones

  resources :historial_estado_usuarios

  resources :asignacion_funciones

  resources :asistencia_eventos

  resources :asignacion_rol_predefinidos

  resources :privilegios

  resources :notificacion_sistemas

  resources :notificacion_emailes

  resources :notificaciones

  resources :evento_publicos

  resources :informe_gastos do
    resources :detalle_gastos #, only: [:new, :create]
  end

  resources :detalle_restricciones

  resources :restricciones

  resources :postulaciones do
	  member do
	    post 'aceptar'
	  end
  end

  resources :notas

  resources :asignacion_roles do
	resources :reportes
  end

  resources :roles

  

  resources :reportes

  resources :asignacion_actividades

  resources :requisitos

  resources :habilidades

  resources :notificacion_predeterminadas

  resources :historial_estado_actividades

  resources :actividades do
  	resources :historial_estado_actividades
  	resources :asignacion_actividades
  end

  resources :objetivo_especificos do
    resources :actividades
  end

  resources :objetivo_generales do
    resources :objetivo_especificos
  end

  resources :historial_estado_proyectos

  resources :proyectos do
	  member do
		  get :agregar_necesidad
	  end
    resources :asignacion_roles
    resources :notificacion_predeterminadas
    resources :historial_estado_proyectos

    get 'notificaciones_predeterminadas' => 'notificacion_predeterminadas#notificaciones_predeterminadas', :as => 'notificaciones_predeterminadas'

    resources :objetivo_generales
    resources :postulaciones
    resources :colaboradores

  end

  resources :necesidades

  resources :voluntarios do
    resources :experiencias 
    resources :horario_disponibles
    resources :notas
   
  end

  resources :horario_disponibles
  
  resources :experiencias
  

  
    get 'buscar_por_legajo/:legajo' => 'voluntarios#buscar_por_legajo'
    get 'buscar_usuario'=>'usuarios#buscar_usuario'
  
  
   get 'buscar_voluntario'=>'voluntarios#buscar_usuario'

  get 'cronograma_actividades'=>'actividades#cronograma_actividades'

  resources :usuarios do
      resources :notificacion_sistemas
  end

  resources :tipo_privilegios

  resources :concepto_gastos

  resources :estado_usuarios

  resources :estado_presupuestos

  resources :tipo_transacciones

  resources :comprobantes

  resources :organizacion_externas

  resources :tipo_roles

  resources :tipo_habilidades do
    resources :habilidades
  end

  resources :tipo_actividades

  resources :tipo_notificaciones

  resources :estvlado_actividades

  resources :tipo_proyectos

  resources :estado_proyectos
  get 'adminitrar_estado_usuario/'  => 'voluntarios#adminitrar_estado_usuario',:as => 'adminitrar_estado_usuario'
  get 'mis_notas/'  => 'voluntarios#mis_notas',:as => 'mis_notas'
  get 'Responder/' => 'notas#Responder',:as =>'Responder'
  get 'buscarusuario/'  => 'voluntarios#buscarusuario',:as => 'buscarusuario'
  get 'buscarusuario/'  => 'voluntarios#buscar_usuario'
  get 'dar_alta_voluntario' => 'usuarios#dar_alta_voluntario', :as => 'dar_alta_voluntario'

  get 'mis_proyectos', :as => 'proyectos/mis_proyectos', :controller => :proyectos
  get 'mis_necesidades', :as => 'necesidades/mis_necesidades', :controller => :necesidades
  
  get 'asignacion_actividad/busqueda_filtrada', :to => 'asignacion_actividades#busqueda_filtrada'

  get 'gestionar_experiencias/:id' => 'voluntarios#gestionar_experiencias', :as => 'gestionar_experiencias'

  get 'agregar_habilidad', :controller => :actividades
  get 'historial_estado_proyectos/modificar', to: 'historial_estado_proyectos#modificar'
  
  get 'usuarios_proyecto', :controller => :asignacion_roles
  
  get 'asignacion_actividad/dar_baja', to: 'asignacion_actividades#dar_baja'
  get 'asignacion_rol/dar_baja', to: 'asignacion_roles#dar_baja'

  get 'crear_organizacion_externa', :controller => :proyectos
  get 'gestionar_presupuesto/:id' => 'presupuestos#gestionar_presupuesto', :as => 'gestionar_presupuesto'
  get 'gestionar_informe_gastos/:id' => 'informe_gastos#gestionar_informe_gastos', :as => 'gestionar_informe_gastos'

  get 'gestionar_restricciones' => 'restricciones#gestionar_restricciones', :as => 'gestionar_restricciones'

  get 'horarios_disponibles/:id' => 'voluntarios#gestion_horarios_disponibles', :as => 'gestion_horarios_disponibles'
  get 'gestionar_nota_P/:id'  => 'voluntarios#gestionar_nota_P',:as => 'gestionar_nota_P'
  get 'gestionar_estado_usuario'=> 'voluntarios#gestionar_estado_usuario',:as =>'gestionar_estado_usuario'
 

  get 'gestionar_habilidades' => 'tipo_habilidades#gestionar_habilidades', :as => 'gestionar_habilidades'

	get 'control_usuario' => 'transacciones#control_usuario', :as => 'control_usuario'

	get 'control_proyecto' => 'transacciones#control_proyecto', :as => 'control_proyecto'

	get 'control_fecha' => 'transacciones#control_fecha', :as => 'control_fecha'

	root :to => "evento_publicos#index"

  get 'gestionar_concepto_gastos' => 'concepto_gastos#gestionar_concepto_gastos', :as => 'gestionar_concepto_gastos'

  get 'evaluar_presupuestos_pendientes' => 'presupuestos#evaluar_presupuestos_pendientes', :as => 'evaluar_presupuestos_pendientes'

  get 'presupuestos_evaluados' => 'presupuestos#presupuestos_evaluados', :as => 'presupuestos_evaluados'
  
  get 'gestionar_estados_presupuestos' => 'estado_presupuestos#gestionar_estados_presupuestos', :as => 'gestionar_estados_presupuestos'

  get 'evaluar_presupuesto/:id' => 'presupuestos#evaluar_presupuesto', :as => 'evaluar_presupuesto'

	get 'auditoria' => 'transacciones#auditoria', :as => 'auditoria'

	get 'reporte_voluntarios' => 'reporte_generados#reporte_voluntarios', :as => 'reporte_voluntarios'
	
	get 'reporte_proyectos' => 'reporte_generados#reporte_proyectos', :as => 'reporte_proyectos'

	get 'reporte_regionales' => 'reporte_generados#reporte_regionales', :as => 'reporte_regionales'

	get 'reporte_generado' => 'reporte_generados#reporte_generado', :as => 'reporte_generado'
	
	get 'reporte_new' => 'reporte_generados#reporte_new', :as => 'reporte_new'

	get 'usuario_bloqueado' => 'usuarios#usuario_bloqueado', :as => 'usuario_bloqueado'

      get 'gestionar_notificaciones' => 'notificacion_predeterminadas#gestionar_notificaciones', :as => 'gestionar_notificaciones'
	 get 'configuraciones_generales' => 'roles#configuraciones_generales', :as => 'configuraciones_generales'

  
  resources :ayudas
  

end

app/controllers/actividades_controller.rb
class ActividadesController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]
 # before_destroy :borrar_asociaciones

  # GET /actividades
  # GET /actividades.json
  def index
		authorize! :index, Actividad
    @actividades = Actividad.all
    @proyecto = @actividades.last.proyecto
		raise CanCan::AccessDenied if !Actividad.accessible_by(current_ability, :index).include?(@actividades.first) 
  end

  # GET /actividades/1
  # GET /actividades/1.json
  def show
		raise CanCan::AccessDenied if !Actividad.accessible_by(current_ability, :show).include?(@actividad) 
    @proyecto = @actividad.proyecto
		
  end
		
  # GET /actividades/new
  def new
    @objetivo_especifico = ObjetivoEspecifico.find(params[:objetivo_especifico_id])
    @actividad = Actividad.new(:objetivo_especifico_id => params[:objetivo_especifico_id])
		authorize! :new, Actividad 
    @proyecto = @actividad.objetivo_especifico.objetivo_general.proyecto
    @habilidades = Habilidad.all
    @tipoActividades = TipoActividad.all
    @actividad.requisitos.build
		
  end

  # GET /actividades/1/edit
  def edit
		@proyecto = @actividad.objetivo_especifico.objetivo_general.proyecto
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @proyecto).count == 1
			raise CanCan::AccessDenied if !Actividad.accessible_by(current_ability, :edit).include?(@actividad)
		else
			authorize! :edit, Actividad
		end
    
    @habilidades = Habilidad.all
    @tipoActividades = TipoActividad.all
		
  end

  # POST /actividades
  # POST /actividades.json
  def create
    @actividad = Actividad.new(actividad_params)
		authorize! :create, Actividad
    @actividad.historial_estado_actividades.new(estado_actividad_id: EstadoActividad.find_by(nombre: 'Creada').id, actividad_id: @actividad.id)
    @habilidades = Habilidad.all
    @tipoActividades = TipoActividad.all
    if params[:actividad][:repetitiva] == "1"
      @actividad.repetitiva = true      
      if params[:actividad][:frecuencia] == 'Por Semana'
        @actividad.frecuencia = 'Por Semana'
        case params[:actividad][:dia_semana]
        when "1"
          @actividad.dia_semana = 'Lunes'
        when "2"
          @actividad.dia_semana = 'Martes'
        when "3"
          @actividad.dia_semana = 'Miércoles'
        when "4"
          @actividad.dia_semana = 'Jueves'
        when "5"
          @actividad.dia_semana = 'Viernes'
        when "6"
          @actividad.dia_semana = 'Sábado'
        when "7"
          @actividad.dia_semana = 'Domingo'
        else
          @actividad.dia_semana = 'No Seleccionado'
        end
      elsif params[:actividad][:frecuencia] == 'Por Mes'
        @actividad.frecuencia = 'Por Mes'
        @actividad.dia_semana = nil
      else
        @actividad.frecuencia = 'No Seleccionado'
      end
    else
      @actividad.repetitiva = false
      @actividad.frecuencia = nil
      @actividad.dia_semana = nil

    end
    @actividad.active = true
		@objetivo_especifico = @actividad.objetivo_especifico
    @proyecto = @actividad.proyecto
    respond_to do |format|
      if @actividad.save
            sesion= Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)
            Transaccion.create!(
		    descripcion: "Creación de la Actividad : #{@actividad.attributes}",
		    sesion_id: sesion.id ,
		    proyecto_id: @actividad.proyecto.id)
	      format.html { redirect_to @actividad,:objetivo_especifico_id => @actividad.objetivo_especifico_id 
		     flash[:success] = 'Actividad fue creada satisfactoriamente.'  }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new, :objetivo_especifico_id => @actividad.objetivo_especifico_id }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividades/1
  # PATCH/PUT /actividades/1.json
  def update
		@proyecto = @actividad.proyecto
		if current_usuario.asignacion_roles.where(esActual: true, id: Rol.where(nombre: "Voluntario"), proyecto: @proyecto) && current_usuario.asignacion_roles.where(esActual: true, proyecto: @proyecto).count == 1
			raise CanCan::AccessDenied if !Actividad.accessible_by(current_ability, :update).include?(@actividad)
		else
			authorize! :update, Actividad
		end
    @habilidades = Habilidad.all
    @tipoActividades = TipoActividad.all
    
    @actividad.assign_attributes(actividad_params)
    if params[:actividad][:repetitiva] == "1"
      @actividad.repetitiva = true      
      if params[:actividad][:frecuencia] == 'Por Semana'
        @actividad.frecuencia = 'Por Semana'
        case params[:actividad][:dia_semana]
        when "1"
          @actividad.dia_semana = 'Lunes'
        when "2"
          @actividad.dia_semana = 'Martes'
        when "3"
          @actividad.dia_semana = 'Miércoles'
        when "4"
          @actividad.dia_semana = 'Jueves'
        when "5"
          @actividad.dia_semana = 'Viernes'
        when "6"
          @actividad.dia_semana = 'Sábado'
        when "7"
          @actividad.dia_semana = 'Domingo'
        else
          @actividad.dia_semana = 'No Seleccionado'
        end
      elsif params[:actividad][:frecuencia] == 'Por Mes'
        @actividad.frecuencia = 'Por Mes'
        @actividad.dia_semana = nil
      else
        @actividad.frecuencia = 'No Seleccionado'
      end
    else
      @actividad.repetitiva = false
      @actividad.frecuencia = nil
      @actividad.dia_semana = nil

    end


    respond_to do |format|
      if @actividad.save
            sesion= Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)
            Transaccion.create!(
		    descripcion: "Actualización de la Actividad #{@actividad.nombre}: #{@actividad.previous_changes}" ,
		    sesion_id: sesion.id ,
		    proyecto_id: @actividad.proyecto.id)
        format.html { redirect_to @actividad
          flash[:success] = 'Actividad fue actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividades/1
  # DELETE /actividades/1.json
  def destroy
		raise CanCan::AccessDenied if !Actividad.accessible_by(current_ability, :destroy).include?(@actividad) 
    @objetivo_especifico = @actividad.objetivo_especifico
    @actividad.active = false
    @actividad.save
    respond_to do |format|
            sesion= Sesion.find_by(usuario_id: current_usuario.id, fechaFin: nil)
            Transaccion.create!(
		    descripcion: "Borrado de la Actividad #{@actividad.attributes}" ,
		    sesion_id: sesion.id ,
		    proyecto_id: @actividad.proyecto.id)
      format.html { redirect_to @objetivo_especifico
		    flash[:success] = 'Actividad fue borrada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  def agregar_habilidad
		authorize! :agregar_habilidad, Actividad
     @habilidad = Habilidad.new
     respond_to do |format|
	format.js {render partial: 'requisitos', content_type: 'text/html', :locals => {:f => params[:f]}}
	format.json {render partial: 'requisitos', content_type: 'text/html', :locals => {:f => params[:f]}}
     end
  end

  def cronograma_actividades
    @proyecto = Proyecto.find(params[:proyecto_id])
    @actividades = @proyecto.actividades.order(:objetivo_especifico_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:nombre, :descripcion, :repetitiva, :frecuencia, :dia_semana, :duracion, :duracionReal, :fechaEstimadaInicio, :fechaRealInicio, :estrategiasIntervencion, :metodologiasIntervencion, :mecanismoEvaluacion, :resultadosEsperados, :objetivo_especifico_id, :proyecto_id, :tipo_actividad_id, requisitos_attributes:  [:id, :actividad_id, :habilidad_id])
    end

end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/views/actividades/_requisitos.html.erb
<%= f.simple_fields_for :requisitos do |requisito| %>
	<%= requisito.input :habilidad_id, collection: @habilidades %>
	<%= requisito.input :actividad_id,:as => :hidden, input_html: {value: :actividad_id} %>
<%end%>

app/views/actividades/cronograma_actividades.html.erb
<h1>Cronograma de Inicio de Actividades</h1>


<%= link_to 'Atrás', @proyecto %>

<div class="row">
<div class="col-lg-12">
<table class="table table-hover table-striped tablesorter actividades">
                <thead>
                  <tr>
                    <th class="col-lg-1" style="text-align:left; width: 40%;">Actividad</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">E</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">F</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">M</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">A</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">M</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">J</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">J</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">A</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">S</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">O</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">N</th>
                    <th class="col-lg-1" style="text-align:center; width: 5%;">D</th>                  
                  </tr>
                </thead>
                <tbody>
					<% @actividades.each do |actividad| %>
 
		                <tr>
		                    <td style="text-align:left"><%= actividad.nombre %></td>
		                    <% if !actividad.fechaEstimadaInicio.blank?  %>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 1  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 2  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 3  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 4  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 5  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 6  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 7  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 8  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 9  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 10  %>X<%end%></td>
			                    <td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 11  %>X<%end%></td>
			                	<td style="text-align:center"><% if actividad.fechaEstimadaInicio.month == 12  %>X<%end%></td>
			                <% else %>
			                	<td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                    <td style="text-align:center"></td>
			                	<td style="text-align:center"></td>
			                <% end %>
		                </tr>
                  
 					<% end %>                 
                </tbody>
              </table>       
</div>
</div>

app/views/actividades/edit.html.erb
<h1>Editing actividad</h1>

<%= render 'form' %>


<%= link_to 'Atrás', @actividad %>

app/views/actividades/index.html.erb
<h1>Listing actividades</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Duracion</th>
      <th>Duracionreal</th>
      <th>Fechaestimadainicio</th>
      <th>Fecharealinicio</th>
      <th>Estrategiasintervencion</th>
      <th>Metodologiasintervencion</th>
      <th>Mecanismoevaluacion</th>
      <th>Resultadosesperados</th>
      <th>Objetivo especifico</th>
      <th>Proyecto</th>
      <th>Tipo actividad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividades.each do |actividad| %>
      <tr>
        <td><%= actividad.nombre %></td>
        <td><%= actividad.descripcion %></td>
        <td><%= actividad.duracion %></td>
        <td><%= actividad.duracionReal %></td>
        <td><%= actividad.fechaEstimadaInicio %></td>
        <td><%= actividad.fechaRealInicio %></td>
        <td><%= actividad.estrategiasIntervencion %></td>
        <td><%= actividad.metodologiasIntervencion %></td>
        <td><%= actividad.mecanismoEvaluacion %></td>
        <td><%= actividad.resultadosEsperados %></td>
        <td><%= actividad.objetivo_especifico %></td>
        <td><%= actividad.proyecto %></td>
        <td><%= actividad.tipo_actividad %></td>
        <td><%= link_to 'Ver', actividad %></td>
        <td><%= link_to 'Editar', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Borrar', actividad, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Actividad', new_actividad_path %>

app/views/actividades/new.html.erb
<h1>Nueva Actividad</h1>

<%= render 'form' %>

<%= link_to 'Atrás', @objetivo_especifico %> 

app/views/actividades/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
   </div>
<% end %>

  <div class="row">

    <div class="col-lg-6">


      <div>
        <strong>Título de la Actividad</strong>:</br>
        <%= @actividad.nombre%>
      </div>
      <div class="modal-footer">
      </div>
      <div style="overflow-wrap: break-word;">
          <strong>Breve Descripción</strong>:</br>
          <%= @actividad.descripcion %>
      </div>
      <div class="modal-footer">
      </div>
      <div class="row">
        <div class="col-lg-4">
        <div>
            <strong>Repetitiva</strong>:</br>
            <%= @actividad.es_repetitiva %>
        </div>
        
        </div>
        <% if !@actividad.frecuencia.blank? %>
        <div class="col-lg-4">
        <div>
            <strong>Frecuencia de Repetición</strong>:</br>
            <%= @actividad.frecuencia %>
        </div>
        </div>
        <% end %>
        <% if !@actividad.dia_semana.blank? %>
        <div class="col-lg-4">
          <div>
              <strong>Día de la Semana</strong>:</br>    
                <%= @actividad.dia_semana %> 
          </div>
        </div>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
      <div style="overflow-wrap: break-word;">
        <strong>Mecanismos de Evaluación</strong>:</br>
        <%= @actividad.mecanismoEvaluacion %>
      </div>
      <div class="modal-footer">
      </div>
      <div style="overflow-wrap: break-word;">
        <strong>Resultados Esperados</strong>:</br>
        <%= @actividad.resultadosEsperados %> 
      </div>
      <div class="modal-footer">
      </div>

    </div> 
   

    <div class="col-lg-6">

        <div class="row">
          <div class="col-lg-6">
            <div>
                <strong>Fecha Estimada Inicio</strong>:</br>
                <%= @actividad.fechaEstimadaInicio%>
            </div>
          </div>
          <div class="col-lg-6">
              <div>
                  <strong>Duración Estimada</strong>:</br>
                  <%= @actividad.duracion %>
              </div>
          </div>
        </div>
          <div class="modal-footer">
          </div>
        <div class="row">
          <div class="col-lg-6">
            <div>
              <strong>Fecha Inicio Real</strong>:</br>
              <%= @actividad.fechaRealInicio %>
            </div>
          </div>
          <div> 
            <strong>Duración Real</strong>:</br>
            <%=  @actividad.duracionReal %>
          </div>
        </div>
          <div class="modal-footer">
          </div>
          
          
          <div style="overflow-wrap: break-word;">
            <strong>Estrategia Intervención</strong>:</br>
            <%= @actividad.estrategiasIntervencion %>
          </div>
          <div class="modal-footer">
          </div>
          <div style="overflow-wrap: break-word;">
            <strong>Metodologías Intervención</strong>:</br>
            <%= @actividad.metodologiasIntervencion %>
          </div>
          <div class="modal-footer">
          </div>
          
          <div>
        	  <strong>Tipo de Actividad</strong>:</br>
        	  <% if !@actividad.tipo_actividad.blank? %>
        		  <%= @actividad.tipo_actividad %>
        	  <% else %>
        		   "No se ha seleccionado ningun Tipo de Actividad"
        	  <% end %>
          </div>
          <div class="modal-footer">
          </div>
          <div>
            <strong>Estado Actividad</strong>:</br>
            <%= @actividad.historial_estado_actividades.last.estado_actividad %>
          </div>
    </div>
  </div><!-- /.row -->
<div class="modal-footer">
</div>




<% if (current_usuario.asignacion_roles.where(esActual: true, active: true, proyecto: @proyecto, rol: Rol.find_by(nombre: "Director")).count > 0) || (current_usuario.asignacion_roles.where(esActual: true, active: true, proyecto: @proyecto, rol: Rol.find_by(nombre: "Coordinador")).count > 0) %>
  <%= link_to 'Editar', edit_actividad_path(@actividad) %> |
  <% if @actividad.borrable %>
         <%= link_to 'Borrar', @actividad, method: :delete, data: { confirm: 'Seguro?' } %> |
  <% end %>
  <%= link_to 'Agregar Requisitos', new_requisito_path(:actividad_id => @actividad.id) %> |
  <%= link_to 'Ver Historial', historial_estado_actividades_path(:actividad_id => @actividad.id)%> |
  <%= link_to 'Asignación de Recursos', asignacion_actividades_path(:actividad_id => @actividad.id)%> |
  <%= link_to 'Ver Reportes', reportes_path(:actividad_id => @actividad.id)%> |
<% elsif current_usuario.participando_actividad(@actividad) > 0 %>
  <%= link_to 'Editar', edit_actividad_path(@actividad) %> |
  <% if @actividad.borrable %>
         <%= link_to 'Borrar', @actividad, method: :delete, data: { confirm: 'Seguro?' } %> |
  <% end %>
  <%= link_to 'Agregar Requisitos', new_requisito_path(:actividad_id => @actividad.id) %> |
  <%= link_to 'Ver Historial', historial_estado_actividades_path(:actividad_id => @actividad.id)%> |
  <%= link_to 'Asignación de Recursos', asignacion_actividades_path(:actividad_id => @actividad.id)%> |
  <%= link_to 'Ver Reportes', reportes_path(:actividad_id => @actividad.id)%> |
<% end %>
<%= link_to 'Atrás', @actividad.objetivo_especifico %>